# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13.5

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/gen0cide/gscript
    steps:
      - checkout

      # Make sure the gscript tool continues to build properly
      - run: go get -u ./...
      - run: go test -v ./...
      - run: cd cmd/gscript
      - run: go build -x -v
      - run: go get github.com/gen0cide/gscript/cmd/gscript
      # Test compiling and running the a gscript bniary
      - run: gscript --debug compile --enable-logging --obfuscation-level=3 --output-file=/go/src/github.com/gen0cide/gscript/stdlib/time/time_test /go/src/github.com/gen0cide/gscript/stdlib/time/time_test.gs 
      - run: chmod +x /go/src/github.com/gen0cide/gscript/stdlib/time/time_test
      - run: /go/src/github.com/gen0cide/gscript/stdlib/time/time_test
      # Test and compile multiple gscripts
      - run: gscript --debug compile --enable-logging --obfuscation-level=3 --output-file=/go/src/github.com/gen0cide/gscript/stdlib/multi_test /go/src/github.com/gen0cide/gscript/stdlib/encoding/encoding_test.gs /go/src/github.com/gen0cide/gscript/stdlib/rand/rand_test.gs /go/src/github.com/gen0cide/gscript/stdlib/exec/exec_test.gs
      - run: chmod +x /go/src/github.com/gen0cide/gscript/stdlib/multi_test
      - run: /go/src/github.com/gen0cide/gscript/stdlib/multi_test
      # Test multiple assets
      - run: gscript --debug compile --enable-logging --obfuscation-level=3 --output-file=/go/src/github.com/gen0cide/gscript/stdlib/file/file_tester /go/src/github.com/gen0cide/gscript/stdlib/file/file_test.gs /go/src/github.com/gen0cide/gscript/stdlib/file/file_test3.gs
      - run: chmod +x /go/src/github.com/gen0cide/gscript/stdlib/file/file_tester
      - run: /go/src/github.com/gen0cide/gscript/stdlib/file/file_tester
      # Test obfuscation
      - run: gscript --debug compile --touch-a-silmaril=true --obfuscation-level=0 --output-file=/go/src/github.com/gen0cide/gscript/stdlib/file/file_test4 /go/src/github.com/gen0cide/gscript/stdlib/file/file_test4.gs
      - run: chmod +x /go/src/github.com/gen0cide/gscript/stdlib/file/file_test4
      - run: /go/src/github.com/gen0cide/gscript/stdlib/file/file_test4
      #- run: cat /go/src/github.com/gen0cide/gscript/stdlib/file/file_test4.txt
      - run: grep -i "github" /go/src/github.com/gen0cide/gscript/stdlib/file/file_test4 || true
      - run: grep -i "go" /go/src/github.com/gen0cide/gscript/stdlib/file/file_test4 || true
